import { StyleSheet, Platform, Dimensions } from "react-native";

/**
 * Centralized styles for NewMatchScreen
 * Organized by feature/section for easier maintenance
 */
const styles = StyleSheet.create({
  // ============ DART SELECTOR & SPECIALTY SHOTS ============
  dartSelectorGrid: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 12,
    marginVertical: 8,
  },
  dartSquare: {
    width: 50,
    height: 50,
    borderWidth: 2,
    borderColor: "#999",
    borderRadius: 8,
    backgroundColor: "#333",
    justifyContent: "center",
    alignItems: "center",
  },
  dartSquareSelected: {
    borderColor: "#4CAF50",
    backgroundColor: "#2A5A2A",
    borderWidth: 3,
  },
  dartSquareWithSpecialty: {
    borderColor: "#4CAF50",
    backgroundColor: "#2A5A2A",
    borderWidth: 3,
  },
  dartSpecialtyIndicator: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  dartSquareMissed: {
    borderColor: "#FF4444",
    backgroundColor: "#5A2A2A",
    borderWidth: 3,
  },
  dartMissedX: {
    fontSize: 32,
    color: "#FF4444",
    fontWeight: "bold",
  },
  dartSquareClosest: {
    borderColor: "#FFD700",
    backgroundColor: "#3A3A00",
    borderWidth: 3,
  },
  dartClosestCheckmark: {
    fontSize: 24,
    color: "#FFD700",
    fontWeight: "bold",
  },

  // ============ DART SPECIALTY MODAL ============
  dartSpecialtyOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  dartSpecialtyContainer: {
    backgroundColor: "#1A1A1A",
    borderRadius: 16,
    padding: 20,
    width: "85%",
    maxWidth: 350,
    borderWidth: 2,
    borderColor: "#4CAF50",
  },
  dartSpecialtyTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 4,
    textAlign: "center",
  },
  dartSpecialtySubtitle: {
    fontSize: 14,
    color: "#CCCCCC",
    marginBottom: 16,
    textAlign: "center",
  },
  dartSpecialtyShotsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
    justifyContent: "center",
  },
  dartSpecialtyShotButton: {
    backgroundColor: "#2A2A2A",
    borderWidth: 2,
    borderColor: "#4CAF50",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    minWidth: "45%",
    alignItems: "center",
  },
  dartSpecialtyShotName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  dartSpecialtyClearButton: {
    backgroundColor: "#444",
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 8,
    alignItems: "center",
  },
  dartSpecialtyClearButtonText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "600",
  },
  dartSpecialtyCloseButton: {
    backgroundColor: "#666",
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
  },
  dartSpecialtyCloseButtonText: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "600",
  },

  // ============ FULLSCREEN LAYOUT ============
  fullscreenContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  topPlayerSection: {
    flex: 1,
  },
  bottomPlayerSection: {
    flex: 1,
  },
  playerSectionHighlighted: {
    borderWidth: 4,
    borderColor: "#FFD700",
    borderRadius: 10,
  },
  whiteBackground: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  gradientClipContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    overflow: "hidden",
  },
  gradientFull: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 20,
  },
  backButtonCircle: {
    position: "absolute",
    top: 40,
    left: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255,255,255,0.8)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  simpleScoreButton: {
    position: "absolute",
    top: 40,
    right: 20,
    width: 70,
    height: 70,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.8)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "#000000",
  },
  simpleScoreButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    letterSpacing: 1,
  },
  playerNameTop: {
    position: "absolute",
    top: "25%",
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    letterSpacing: 2,
    zIndex: 5,
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  playerNameBottom: {
    position: "absolute",
    top: "25%",
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    letterSpacing: 2,
    zIndex: 5,
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  scoreSectionFullscreen: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  scoreHalfTapArea: {
    flex: 1,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  scoreCenter: {
    position: "absolute",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    pointerEvents: "none",
  },
  minusPlusTextLarge: {
    fontSize: 80,
    color: "#333",
    fontWeight: "bold",
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  scoreNumberLarge: {
    fontSize: 140,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    textShadowColor: "#FFFFFF",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 1,
  },
  statTrackButtonSquare: {
    position: "absolute",
    bottom: 30,
    left: 20,
    width: 70,
    height: 70,
    backgroundColor: "rgba(255,255,255,0.8)",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
    borderWidth: 1,
    borderColor: "#000000",
  },
  statTrackText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    letterSpacing: 1,
  },
  incrementGrid: {
    position: "absolute",
    bottom: 30,
    right: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    width: 140,
    gap: 8,
    zIndex: 10,
  },
  incrementButton: {
    width: 66,
    height: 50,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#000000",
  },
  incrementButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },

  // ============ SETUP SCREENS ============
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    ...(Platform.OS === "web" && {
      maxWidth: 1200,
      alignSelf: "center",
      width: "100%",
    }),
  },
  setupContainer: {
    padding: 20,
    justifyContent: "center",
  },
  lobbyCenteredContainer: {
    padding: 20,
    justifyContent: "center",
    minHeight: "100%",
  },
  largeButtonContainer: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    alignItems: "stretch",
  },
  largeImageButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginVertical: 10,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    overflow: "hidden",
  },
  largeImageButtonDisabled: {
    opacity: 0.5,
  },
  buttonImage: {
    width: "100%",
    height: "70%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  imageBackground: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  imageOverlay: {
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  overlayText: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  comingSoonText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 8,
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  mediumImageButton: {
    flex: 0.3,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginVertical: 8,
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    overflow: "hidden",
  },
  imagePlaceholder: {
    width: "100%",
    height: "70%",
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  imagePlaceholderSmall: {
    width: "100%",
    height: "60%",
    backgroundColor: "#F0F0F0",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  placeholderText: {
    fontSize: 18,
    color: "#999",
    fontStyle: "italic",
  },
  placeholderTextSmall: {
    fontSize: 14,
    color: "#999",
    fontStyle: "italic",
  },
  largeButtonText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    marginVertical: 15,
  },
  mediumButtonText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#333",
    marginVertical: 12,
  },
  disabledButtonText: {
    color: "#999",
  },
  titleCentered: {
    textAlign: "center",
    marginBottom: 20,
    marginTop: 40,
    fontWeight: "bold",
  },
  subtitleCentered: {
    textAlign: "center",
    marginBottom: 16,
    color: "#666",
  },
  featureDescription: {
    color: "#666",
    marginBottom: 16,
    textAlign: "center",
  },
  featureList: {
    paddingHorizontal: 24,
  },
  featureItem: {
    color: "#666",
    fontSize: 16,
    paddingVertical: 6,
    lineHeight: 24,
  },
  backButtonAbsolute: {
    position: "absolute",
    top: 10,
    left: 10,
    zIndex: 10,
  },
  cancelButtonAbsolute: {
    marginTop: 20,
  },
  title: {
    marginBottom: 24,
    textAlign: "center",
    fontWeight: "bold",
  },
  input: {
    marginBottom: 16,
  },
  playerSetupCard: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
  },
  quickBracketSurface: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    marginBottom: 20,
    elevation: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  quickBracketLabel: {
    fontWeight: "600",
    color: "#333",
  },
  quickBracketButton: {
    flex: 1,
    marginLeft: 12,
  },
  playerSetupRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  playerSetupRowReordered: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  profilePicPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: "#E0E0E0",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#CCC",
  },
  profileIconText: {
    fontSize: 28,
  },
  colorIndicator: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 2,
    borderColor: "#ddd",
    overflow: "hidden",
  },
  colorIndicatorRounded: {
    width: 50,
    height: 50,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ddd",
    overflow: "hidden",
  },
  colorIndicatorFull: {
    width: "100%",
    height: "100%",
  },
  colorIndicatorGradient: {
    width: "100%",
    height: "100%",
  },
  playerNameInput: {
    flex: 1,
  },
  colorPicker: {
    flexDirection: "row",
    marginTop: 8,
  },
  colorButton: {
    width: 40,
    height: 40,
    marginRight: 8,
    minWidth: 40,
  },
  addPlayerButton: {
    marginBottom: 12,
  },
  matchTypeButton: {
    marginBottom: 16,
    paddingVertical: 8,
  },
  backButton: {
    alignSelf: "flex-start",
    marginBottom: 8,
  },
  teamSetupCard: {
    backgroundColor: "white",
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    elevation: 2,
  },
  colorLabel: {
    marginTop: 8,
    marginBottom: 4,
    color: "#666",
  },
  startButton: {
    marginTop: 8,
    marginBottom: 8,
  },
  cancelButton: {
    marginTop: 4,
  },
  error: {
    color: "#d32f2f",
    marginBottom: 12,
    textAlign: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
  },
  headerTitle: {
    fontWeight: "bold",
  },
  scoreContainer: {
    padding: 20,
  },
  playerCard: {
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    elevation: 2,
  },
  playerCardGradient: {
    width: "100%",
    borderRadius: 12,
  },
  playerCardContent: {
    padding: 24,
    borderRadius: 12,
    alignItems: "center",
  },
  winnerCard: {
    borderWidth: 3,
    borderColor: "#FFD700",
  },
  playerName: {
    marginBottom: 12,
    fontWeight: "bold",
    color: "white",
  },
  progressBarContainer: {
    width: "100%",
    height: 24,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    borderRadius: 12,
    transition: "width 0.3s ease",
  },
  scoreSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  score: {
    marginHorizontal: 20,
    fontWeight: "bold",
    minWidth: 80,
    textAlign: "center",
    color: "white",
  },
  quickScoreContainer: {
    flexDirection: "row",
    marginTop: 12,
    gap: 8,
  },
  quickScoreLeft: {
    flex: 1,
  },
  quickScoreRight: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
    justifyContent: "space-between",
  },
  quickScoreChip: {
    width: "48%",
    marginBottom: 4,
    borderColor: "white",
  },
  statTrackButton: {
    height: "100%",
  },
  statsButton: {
    marginTop: 8,
  },
  vs: {
    textAlign: "center",
    color: "#999",
    fontWeight: "bold",
    marginVertical: 8,
  },
  actions: {
    padding: 20,
    paddingTop: 0,
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flex: 1,
  },
  simplifiedOverlay: {
    padding: 20,
    justifyContent: "center",
  },
  overlayContent: {
    padding: 24,
    borderRadius: 16,
    backgroundColor: "white",
  },
  overlayTitle: {
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
  },
  overlayDescription: {
    marginBottom: 20,
    textAlign: "center",
    color: "#666",
  },
  overlayPlayerSection: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
  },
  overlayPlayerName: {
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
  },
  overlayLabel: {
    fontSize: 14,
    marginBottom: 8,
    color: "#666",
  },
  dartButtonsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 12,
  },
  dartChip: {
    minWidth: 60,
  },
  overlayInput: {
    marginBottom: 12,
  },
  closestButton: {
    width: "100%",
  },
  overlayActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  overlayActionButton: {
    flex: 1,
  },
  statsInstruction: {
    marginBottom: 16,
    color: "#666",
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  statLabel: {
    fontSize: 16,
    fontWeight: "500",
  },
  statControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  statValue: {
    fontSize: 18,
    fontWeight: "bold",
    minWidth: 40,
    textAlign: "center",
  },
  winnerText: {
    textAlign: "center",
    fontWeight: "bold",
    marginBottom: 8,
    color: "#FFD700",
  },
  finalScore: {
    textAlign: "center",
    marginBottom: 16,
    fontSize: 18,
  },
  victoryDialog: {
    backgroundColor: "white",
  },
  victoryContent: {
    alignItems: "center",
    paddingVertical: 50,
    paddingTop: 60,
    backgroundColor: "white",
  },
  victoryTitle: {
    fontWeight: "bold",
    marginBottom: 24,
    textAlign: "center",
  },
  victoryScore: {
    fontSize: 72,
    fontWeight: "bold",
    marginBottom: 24,
    marginTop: 10,
    color: "#1976d2",
  },
  victorySubtext: {
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 20,
  },
  victoryActions: {
    justifyContent: "space-around",
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: "white",
  },
  victoryButton: {
    minWidth: 120,
  },
  selectColorButton: {
    marginTop: 8,
    marginBottom: 8,
  },

  // ============ COLOR PICKER MODAL ============
  colorPickerModal: {
    backgroundColor: "#000000",
    margin: 0,
    width: "100%",
    height: "100%",
  },
  colorPickerContainer: {
    flex: 1,
    backgroundColor: "#000000",
    paddingTop: 60,
    paddingBottom: 20,
  },
  colorPickerTitle: {
    textAlign: "center",
    marginBottom: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    paddingHorizontal: 20,
  },
  colorScrollView: {
    flex: 1,
  },
  colorListVertical: {
    paddingHorizontal: 30,
    paddingBottom: 20,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  colorItemLarge: {
    width: "44%",
    height: 160,
    marginBottom: 25,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#888888",
    overflow: "hidden",
    position: "relative",
  },
  colorItemOwned: {
    borderColor: "#4CAF50",
    borderWidth: 3,
  },
  colorItemSelected: {
    borderColor: "#007AFF",
    borderWidth: 4,
  },
  colorItemTaken: {
    borderColor: "#1A237E",
    borderWidth: 3,
    opacity: 0.5,
  },
  colorItemFaded: {
    opacity: 0.5,
  },
  colorItemGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  colorNameVerticalContainer: {
    position: "absolute",
    left: 8,
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    width: 30,
  },
  colorNameVertical: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    transform: [{ rotate: "-90deg" }],
    transformOrigin: "center",
    width: 120,
    textAlign: "center",
  },
  selectionIndicator: {
    position: "absolute",
    top: 8,
    right: 8,
  },
  otherPlayerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    justifyContent: "center",
    alignItems: "center",
  },
  checkmarkCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
  },
  checkmarkText: {
    color: "#000000",
    fontSize: 18,
    fontWeight: "bold",
  },
  takenText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 8,
  },
  continueButton: {
    marginHorizontal: 20,
    marginTop: 10,
    paddingVertical: 8,
  },

  // ============ BACK CONFIRMATION DIALOG ============
  backConfirmDialog: {
    backgroundColor: "#000000",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  backConfirmContent: {
    paddingVertical: 20,
  },
  backConfirmText: {
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 10,
  },
  backConfirmSubtext: {
    color: "#CCCCCC",
    textAlign: "center",
  },
  backConfirmActions: {
    flexDirection: "column",
    paddingHorizontal: 20,
    paddingVertical: 10,
    gap: 12,
  },
  cancelBackButton: {
    borderWidth: 1,
    borderColor: "#FFFFFF",
    width: "100%",
  },
  confirmBackButton: {
    width: "100%",
    paddingVertical: 4,
  },

  // ============ STAT TRACKING MODAL ============
  statTrackModal: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  statTrackContainer: {
    backgroundColor: "#000000",
    borderRadius: 20,
    padding: 24,
    width: "90%",
    maxWidth: 500,
  },
  statTrackTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  statTrackSubtitle: {
    fontSize: 14,
    color: "#CCCCCC",
    textAlign: "center",
    marginBottom: 12,
  },
  statTrackPlayerName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 24,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  statGridItem: {
    width: "48%",
    marginBottom: 20,
  },
  statGridLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  statGridControls: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statButton: {
    width: 40,
    height: 40,
    backgroundColor: "#007AFF",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  statButtonText: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "bold",
  },
  statGridValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    minWidth: 40,
    textAlign: "center",
  },
  statTrackSaveButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 16,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: "#000000",
  },
  statTrackSaveButtonText: {
    color: "#000000",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },

  // ============ QUICK SCORE MODAL ============
  quickScoreOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  quickScoreScrollContainer: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  quickScoreContainerModal: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    padding: 24,
    width: "90%",
    maxWidth: 400,
    minHeight: 550,
    maxHeight: 600,
  },
  quickScoreTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  quickScoreSubtitle: {
    fontSize: 14,
    color: "#CCCCCC",
    textAlign: "center",
    marginBottom: 24,
  },
  quickScorePlayerSection: {
    marginBottom: 24,
  },
  quickScorePlayerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  quickScorePlayerName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  quickScorePlayerCalculation: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4CAF50",
    fontFamily: "monospace",
  },
  quickScoreInputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quickScoreLabel: {
    fontSize: 14,
    color: "#CCCCCC",
  },
  quickScoreControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  quickScoreButton: {
    width: 40,
    height: 40,
    backgroundColor: "#007AFF",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  quickScoreButtonText: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "bold",
  },
  quickScoreValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    minWidth: 40,
    textAlign: "center",
  },
  quickScoreClosestSection: {
    marginBottom: 24,
  },
  quickScoreClosestButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 12,
  },
  quickScorePlayerButton: {
    flex: 1,
    paddingVertical: 12,
    backgroundColor: "#333333",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#555555",
  },
  quickScorePlayerButtonSelected: {
    backgroundColor: "#007AFF",
    borderColor: "#007AFF",
  },
  quickScorePlayerButtonDisabled: {
    backgroundColor: "#333",
    borderColor: "#555",
    opacity: 0.5,
  },
  quickScorePlayerButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
  },
  quickScorePlayerButtonTextDisabled: {
    color: "#666",
  },
  quickScoreStatTrackerSection: {
    marginTop: 8,
    marginBottom: 16,
    alignItems: "center",
  },
  quickScoreStatTrackerButton: {
    backgroundColor: "#2A2A2A",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#4CAF50",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  quickScoreStatTrackerText: {
    color: "#4CAF50",
    fontSize: 16,
    fontWeight: "600",
  },
  quickScoreStatTrackerActiveText: {
    color: "#4CAF50",
    fontSize: 12,
    fontWeight: "bold",
  },
  quickScoreComingSoonText: {
    color: "#666",
    fontSize: 12,
    fontStyle: "italic",
  },
  quickScoreCalculationSection: {
    marginTop: 20,
    marginBottom: 16,
    padding: 16,
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4CAF50",
  },
  quickScoreCalculationText: {
    color: "#4CAF50",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  quickScoreActions: {
    flexDirection: "row",
    gap: 12,
  },
  quickScoreCancelButton: {
    flex: 1,
    paddingVertical: 16,
    backgroundColor: "#333333",
    borderRadius: 12,
  },
  quickScoreCancelButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  quickScoreApplyButton: {
    flex: 1,
    paddingVertical: 16,
    backgroundColor: "#4CAF50",
    borderRadius: 12,
  },
  quickScoreApplyButtonDisabled: {
    backgroundColor: "#666666",
    opacity: 0.5,
  },
  quickScoreApplyButtonText: {
    color: "#000000",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },

  // ============ WASH ROUND DIALOG ============
  washOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    justifyContent: "center",
    alignItems: "center",
  },
  washDialogContainer: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#FFD700",
    padding: 20,
    width: "88%",
    maxWidth: 360,
  },
  washDialogTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFD700",
    textAlign: "center",
    marginBottom: 12,
  },
  washDialogMessage: {
    fontSize: 16,
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 24,
  },
  washDialogActions: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  washButton: {
    flex: 1,
  },

  // ============ PRE-GAME MODAL ============
  preGameOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  preGameContainer: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    padding: 30,
    width: "85%",
    maxWidth: 450,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#333",
  },
  preGameTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#FFF",
    marginBottom: 15,
    textAlign: "center",
  },
  preGameInstruction: {
    fontSize: 16,
    color: "#CCC",
    marginBottom: 30,
    textAlign: "center",
    lineHeight: 22,
  },
  preGameWinnerSection: {
    width: "100%",
    alignItems: "center",
  },
  preGameLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFF",
    marginBottom: 15,
  },
  preGameButtonsRow: {
    flexDirection: "row",
    gap: 15,
    width: "100%",
  },
  preGamePlayerButton: {
    flex: 1,
    backgroundColor: "#007AFF",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  preGamePlayerButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  preGameWinnerText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 25,
    textAlign: "center",
  },
  preGameChoiceLabel: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFF",
    marginBottom: 20,
    textAlign: "center",
  },
  preGameButtonsColumn: {
    width: "100%",
    gap: 15,
  },
  preGameChoiceButton: {
    backgroundColor: "#FF9800",
    paddingVertical: 18,
    borderRadius: 12,
    alignItems: "center",
  },
  preGameChoiceButtonText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "bold",
  },
  preGameChoiceSubtext: {
    color: "#000",
    fontSize: 12,
    fontStyle: "italic",
    marginTop: 4,
  },
  coinFlipContainer: {
    width: "100%",
    height: 300,
    justifyContent: "space-around",
    alignItems: "center",
    marginVertical: 30,
  },
  playerNameContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  playerName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#CCC",
    textAlign: "center",
  },
  winnerFlashContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  coinFlipDisplay: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  coinFlipText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFF",
    textAlign: "center",
    paddingHorizontal: 10,
  },
  coinFlipButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFF",
    textAlign: "center",
  },

  // ============ TOURNAMENT STYLES ============
  tournamentRound: {
    marginBottom: 24,
  },
  roundTitle: {
    fontWeight: "bold",
    marginBottom: 12,
    textAlign: "center",
    color: "#2196F3",
  },
  bracketMatch: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    borderWidth: 2,
    borderColor: "#E0E0E0",
  },
  bracketMatchCompleted: {
    backgroundColor: "#F5F5F5",
    borderColor: "#4CAF50",
  },
  bracketMatchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  bracketPlayerName: {
    fontSize: 16,
    color: "#333",
  },
  bracketWinner: {
    fontWeight: "bold",
    color: "#4CAF50",
  },
  winnerIcon: {
    fontSize: 20,
  },
  tapToPlayText: {
    textAlign: "center",
    color: "#2196F3",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 8,
  },
  bracketHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  bracketHeaderTitle: {
    flex: 1,
    textAlign: "center",
    marginRight: 40,
  },
  zoomControlBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  zoomText: {
    fontSize: 14,
    fontWeight: "600",
    marginHorizontal: 12,
    minWidth: 50,
    textAlign: "center",
  },
  bracketContainer: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  roundLabel: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2196F3",
    textAlign: "center",
  },
  matchCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 10,
    borderWidth: 2,
    borderColor: "#E0E0E0",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  matchCardCompleted: {
    borderColor: "#4CAF50",
    backgroundColor: "#FAFAFA",
  },
  matchCardFuture: {
    borderColor: "#BDBDBD",
    backgroundColor: "#F5F5F5",
    opacity: 0.8,
  },
  playerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  winnerRow: {
    backgroundColor: "#E8F5E9",
  },
  colorIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    overflow: "hidden",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  colorGradient: {
    width: "100%",
    height: "100%",
  },
  colorSolid: {
    width: "100%",
    height: "100%",
  },
  playerText: {
    fontSize: 15,
    color: "#333",
    flex: 1,
  },
  winnerText: {
    fontWeight: "bold",
    color: "#2E7D32",
  },
  tbdText: {
    fontStyle: "italic",
    color: "#999",
    fontSize: 13,
  },
  scoreText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
    marginLeft: 10,
  },
  winnerScore: {
    color: "#2E7D32",
    fontWeight: "bold",
  },
  matchDivider: {
    height: 1,
    backgroundColor: "#E0E0E0",
    marginVertical: 6,
  },
  playIndicator: {
    marginTop: 8,
    paddingVertical: 4,
    backgroundColor: "#E3F2FD",
    borderRadius: 5,
    alignItems: "center",
  },
  playIndicatorInProgress: {
    backgroundColor: "#FFE0B2",
  },
  playText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#1976D2",
    letterSpacing: 0.5,
  },
  seedCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E0E0E0",
    padding: 10,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  seedCardCompleted: {
    borderColor: "#E0E0E0",
    backgroundColor: "#F5F5F5",
    opacity: 0.6,
  },
  seedCardFuture: {
    borderColor: "#BDBDBD",
    backgroundColor: "#F5F5F5",
    opacity: 0.7,
  },
  seedCardNextUp: {
    borderColor: "#2196F3",
    borderWidth: 3,
    backgroundColor: "#E3F2FD",
    shadowColor: "#2196F3",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  seedCardInProgress: {
    borderColor: "#FF9800",
    borderWidth: 3,
    backgroundColor: "#FFF3E0",
    shadowColor: "#FF9800",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 5,
  },
  teamRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 4,
  },
  teamRowWinner: {
    backgroundColor: "#E8F5E9",
  },
  teamColorDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    overflow: "hidden",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#DDD",
  },
  teamName: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  teamNameWinner: {
    fontWeight: "bold",
    color: "#2E7D32",
  },
  teamNameTbd: {
    fontStyle: "italic",
    color: "#999",
    fontSize: 12,
  },
  teamScore: {
    fontSize: 15,
    fontWeight: "600",
    color: "#666",
    marginLeft: 8,
  },
  teamScoreWinner: {
    color: "#2E7D32",
    fontWeight: "bold",
  },
  seedDivider: {
    height: 1,
    backgroundColor: "#E0E0E0",
    marginVertical: 6,
  },

  // ============ MATCH RESULTS MODAL ============
  winnerBanner: {
    backgroundColor: "#4CAF50",
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
    alignItems: "center",
  },
  winnerLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  winnerName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  matchSummaryCard: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    width: "100%",
    minWidth: 300,
  },
  matchSummaryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 12,
  },
  playerResultRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 6,
    marginBottom: 8,
    backgroundColor: "#F5F5F5",
    minWidth: 250,
    width: "100%",
  },
  playerResultRowWinner: {
    backgroundColor: "#E8F5E9",
  },
  playerResultName: {
    fontSize: 16,
    color: "#333",
  },
  playerResultNameWinner: {
    fontWeight: "bold",
    color: "#2E7D32",
  },
  playerResultScore: {
    fontSize: 20,
    fontWeight: "600",
    color: "#666",
    minWidth: 50,
    textAlign: "right",
  },
  playerResultScoreWinner: {
    color: "#2E7D32",
    fontWeight: "bold",
  },
  statsComingSoon: {
    marginTop: 16,
    padding: 16,
    backgroundColor: "#FFF3E0",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FFB74D",
  },
  statsComingSoonTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#E65100",
    marginBottom: 8,
  },
  statsComingSoonText: {
    fontSize: 14,
    color: "#E65100",
    fontStyle: "italic",
  },

  // ============ ROUND TRACKER ============
  roundTrackerContainer: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: [{ translateX: -75 }, { translateY: -75 }],
    width: 150,
    height: 150,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5,
  },
  roundTrackerBox: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    borderWidth: 3,
    borderColor: "#FFD700",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 15,
  },
  roundTrackerLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFD700",
    letterSpacing: 2,
    marginBottom: 4,
  },
  roundTrackerNumber: {
    fontSize: 56,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  roundTrackerHint: {
    fontSize: 10,
    fontWeight: "600",
    color: "#CCCCCC",
    letterSpacing: 1,
  },

  // ============ ROUND SUMMARY DIALOG ============
  roundSummaryOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  roundSummaryContainer: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    padding: 24,
    width: "85%",
    maxWidth: 420,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  roundSummaryTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#FFD700",
    textAlign: "center",
    marginBottom: 24,
    letterSpacing: 1.5,
  },
  roundSummaryContent: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginBottom: 28,
    paddingVertical: 16,
  },
  roundPlayerStats: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 12,
  },
  roundPlayerName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 12,
    textAlign: "center",
  },
  roundDarts: {
    fontSize: 18,
    fontWeight: "600",
    color: "#4CAF50",
    marginBottom: 8,
  },
  roundPoints: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFD700",
  },
  roundVsDivider: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FFD700",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 12,
  },
  roundVsText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1A1A1A",
    letterSpacing: 1,
  },
  roundWinnerSection: {
    backgroundColor: "#2A2A2A",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#4CAF50",
    alignItems: "center",
  },
  roundWinnerLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#CCCCCC",
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  roundWinnerName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 8,
  },
  roundWinnerPoints: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFD700",
  },
  roundTieText: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#CCCCCC",
    letterSpacing: 1,
  },
  roundSummaryActions: {
    flexDirection: "row",
    gap: 12,
  },
  roundSummaryActionButton: {
    flex: 1,
    borderRadius: 12,
  },
  roundCancelButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: "#333333",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#555555",
    alignItems: "center",
  },
  roundCancelButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  roundSubmitButton: {
    flex: 1,
    paddingVertical: 14,
    backgroundColor: "#4CAF50",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4CAF50",
    alignItems: "center",
  },
  roundSubmitButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000000",
    letterSpacing: 1,
  },
  roundBreakdownSection: {
    marginTop: 20,
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#FFD700",
  },
  roundBreakdownTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFD700",
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: 1.2,
  },
  roundBreakdownHeader: {
    flexDirection: "row",
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: "#FFD700",
  },
  roundBreakdownHeaderText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
  },
  roundBreakdownRow: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#444444",
  },
  roundNumberText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
  },
  roundBreakdownColumn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  roundNumberColumn: {
    flex: 0.6,
  },
  playerDartsColumn: {
    flex: 1,
    paddingHorizontal: 4,
  },
  roundBreakdownClosest: {
    backgroundColor: "#4CAF50",
    borderRadius: 8,
    paddingVertical: 4,
  },
  roundDartsText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
  },

  // ============ MATCH SUMMARY MODAL ============
  matchSummaryOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: Platform.OS === "web" ? 0 : 16,
  },
  matchSummaryContainer: {
    backgroundColor: "#1A1A1A",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#4CAF50",
    width: Platform.OS === "web" ? 420 : "100%",
    maxWidth:
      Platform.OS === "web" ? 420 : Dimensions.get("window").width * 0.95,
    maxHeight: Dimensions.get("window").height * 0.85,
    flexDirection: "column",
  },
  matchSummaryScrollView: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  matchSummaryButtonContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 8,
    gap: 12,
    backgroundColor: "#1A1A1A",
    borderTopWidth: 1,
    borderTopColor: "#333",
  },
  matchSummaryDialog: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#4CAF50",
    maxWidth:
      Platform.OS === "web" ? 340 : Dimensions.get("window").width * 0.9,
    width: Platform.OS === "web" ? 340 : "90%",
    alignSelf: "center",
    maxHeight: Dimensions.get("window").height * 0.8,
  },
  matchSummaryDialogContent: {
    paddingVertical: 24,
    paddingHorizontal: 20,
    backgroundColor: "#1A1A1A",
    backgroundImage: null,
    maxHeight: Dimensions.get("window").height * 0.7,
  },
  matchSummaryHeaderSection: {
    alignItems: "center",
    marginBottom: 24,
  },
  matchSummaryDialogTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#4CAF50",
    textAlign: "center",
    letterSpacing: 1.5,
  },
  matchSummaryRoundsText: {
    fontSize: 14,
    color: "#CCCCCC",
    marginTop: 6,
    fontWeight: "500",
  },
  matchSummaryDialogActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 12,
    paddingBottom: 16,
    gap: 12,
  },
  simpleStatsSection: {
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: "#2A2A2A",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  comparativeStatsSection: {
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: "#2A2A2A",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  statsHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: "#4CAF50",
  },
  statsPlayerName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#4CAF50",
    flex: 1,
    textAlign: "center",
  },
  statsCategory: {
    marginBottom: 12,
  },
  statsCategoryLabel: {
    fontSize: 12,
    color: "#CCCCCC",
    marginBottom: 6,
    textAlign: "center",
  },
  statsValueRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 8,
  },
  statsValueBox: {
    flex: 1,
    backgroundColor: "#1A1A1A",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#444",
  },
  statsValueHighlight: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
  },
  statsValueText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
  },
  statRowSimple: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#333",
  },
  statLabelSimple: {
    fontSize: 13,
    color: "#CCCCCC",
    fontWeight: "500",
  },
  statValueSimple: {
    fontSize: 13,
    color: "#4CAF50",
    fontWeight: "bold",
  },
  matchSummaryTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#4CAF50",
    textAlign: "center",
    marginBottom: 24,
    letterSpacing: 1.5,
  },
  matchWinnerSection: {
    backgroundColor: "#2A2A2A",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "#FFD700",
    alignItems: "center",
  },
  matchWinnerLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFD700",
    letterSpacing: 1.5,
    marginBottom: 8,
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  matchWinnerName: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 12,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  matchFinalScore: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#FFFFFF",
    letterSpacing: 2,
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  matchStatsSection: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
    paddingVertical: 16,
  },
  matchPlayerStats: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#2A2A2A",
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 8,
    minWidth: 0,
  },
  matchPlayerStatsName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 12,
    textAlign: "center",
    flexShrink: 1,
  },
  matchStatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    gap: 8,
  },
  matchStatLabel: {
    fontSize: 14,
    color: "#CCCCCC",
    fontWeight: "600",
  },
  matchStatValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4CAF50",
  },
  matchStatDivider: {
    height: 1,
    backgroundColor: "#444444",
    marginVertical: 8,
    width: "100%",
  },

  // ============ STAT TRACKER MODAL (Bottom Sheet) ============
  statTrackerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    justifyContent: "flex-end",
  },
  statTrackerContainer: {
    backgroundColor: "#1A1A1A",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "70%",
    minHeight: "55%",
    flexDirection: "column",
  },
  statTrackerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#4CAF50",
  },
  statTrackerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#4CAF50",
  },
  statTrackerCloseButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  statTrackerCloseText: {
    fontSize: 24,
    color: "#FFFFFF",
  },
  statTrackerContent: {
    flex: 1,
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  statTrackerPlayerSection: {
    marginBottom: 24,
  },
  statTrackerPlayerName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4CAF50",
    marginBottom: 12,
  },
  statTrackerShotsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  statTrackerShotButton: {
    backgroundColor: "#2A2A2A",
    borderWidth: 2,
    borderColor: "#4CAF50",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    minWidth: "45%",
  },
  statTrackerShotName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
  },
  statTrackerSelectedShots: {
    marginTop: 12,
  },
  statTrackerSelectedLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#CCCCCC",
    marginBottom: 8,
  },
  statTrackerChipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  statTrackerChip: {
    backgroundColor: "#4CAF50",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
  },
  statTrackerChipText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000000",
  },
  statTrackerChipRemove: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  statTrackerChipRemoveText: {
    fontSize: 14,
    color: "#000000",
    fontWeight: "bold",
  },
  statTrackerDivider: {
    backgroundColor: "#4CAF50",
    marginVertical: 8,
  },
  statTrackerActions: {
    flexDirection: "row",
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: "#4CAF50",
  },
  statTrackerClearButton: {
    flex: 1,
    backgroundColor: "#444444",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  statTrackerClearButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  statTrackerDoneButton: {
    flex: 1,
    backgroundColor: "#4CAF50",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  statTrackerDoneButtonText: {
    color: "#000000",
    fontSize: 14,
    fontWeight: "bold",
  },
});

export default styles;
